# Generated by Django 3.2 on 2022-07-09 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import videorooms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=videorooms.models.create_room_token, max_length=32)),
                ('max_guests', models.IntegerField(default=5)),
                ('screen_sharing_enabled', models.BooleanField(default=False)),
                ('presentation_enabled', models.BooleanField(default=False)),
                ('chat_enabled', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('guests_input_control', models.BooleanField(default=False)),
                ('guests', models.ManyToManyField(related_name='current_rooms', to=settings.AUTH_USER_MODEL)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hosting_room', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoRoomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='videorooms.videoroom')),
            ],
        ),
    ]
