# Generated by Django 3.2 on 2022-07-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videorooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoroom',
            name='password',
            field=models.CharField(default='', max_length=32),
        ),
    ]
