# Generated by Django 3.2 on 2022-07-11 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videorooms', '0002_videoroom_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoroom',
            name='guests',
            field=models.ManyToManyField(blank=True, related_name='current_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
