# Generated by Django 4.0.5 on 2022-08-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videorooms', '0003_alter_videoroom_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoroom',
            name='password',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
