# Generated by Django 4.0.5 on 2022-08-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videorooms', '0004_alter_videoroom_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoroom',
            name='max_guests',
            field=models.IntegerField(default=3),
        ),
    ]
