# Generated by Django 4.0.5 on 2022-08-28 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videorooms', '0006_videoroom_guests_muted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoRoomMessage',
        ),
    ]
