# Generated by Django 4.0.5 on 2022-08-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionplan_can_create_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
