# Generated by Django 4.0.5 on 2022-08-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_membership_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_plan_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
