# Generated by Django 4.0.5 on 2022-08-10 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_membership_stripe_id_subscriptionplan_stripe_plan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='subscriptions.subscriptionplan'),
        ),
    ]
