# Generated by Django 4.0.5 on 2022-12-22 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_alter_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='subscriptions.subscriptionplan'),
        ),
    ]
