# Generated by Django 4.0.5 on 2022-08-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='is_success',
            new_name='is_complete',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
